apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver
spec:
  selector:
    matchLabels:
      app: driver
  template:
    metadata:
      labels:
        app: driver
    spec:
      containers:
        - name: driver
          image: sidartasilva/fullcycle-maratona-1-codelivery-part-5-driver:latest
          ports:
            - containerPort: 8081
