apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-25fbc2af-911e-406e-bb21-c4484be74ec4
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: data
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: elasticsearch-master-elasticsearch-master-2
    namespace: logs
  gcePersistentDisk:
    pdName: gke-pv-2
    fsType: ext4
